@startuml
actor Cliente
actor Restaurante

rectangle {
  Cliente --> (Ver menú)
  (Ver menú) --> Restaurante
  Cliente --> (Pedir comida)
  (Pedir comida) --> Restaurante
  Restaurante --> (Entregar comida)
}
@enduml
