@startuml
class Cliente {
  -nombre: string
  -direccion: string
  -telefono: string
  +verMenu(): void
  +hacerPedido(): void
}

class Restaurante extends Cliente {
  +mostrarMenu(): void
  +entregarComida(): void
}
@enduml
